version: "3.8"
services:
  jupyter:
    privileged: true
    build:
        context: .
        args:
          - USER_ID=$UID
          - USER_NAME=$USER
    network_mode: host
    ports:
      - "8888:8888"
    environment:
        - DISPLAY=$DISPLAY
        - XAUTHORITY=/home/$USER/.Xauthority
    volumes: 
      - ./:/work:rw
      - $XAUTHORITY:/home/$USER/.Xauthority
